In [78]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [79]:
pd.set_option('display.max_columns',None)

In [80]:
df=pd.read_csv("C:/Users/jishn/Desktop/AI-Powered Healthcare Risk & Patient Intelligence/HOSPITAL DATA/diabetic_data.csv")

In [81]:
df

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,?,Pediatrics-Endocrinology,41,0,1,0,0,0,250.83,?,?,1,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,?,?,59,0,18,0,0,0,276,250.01,255,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,?,?,11,5,13,2,0,1,648,250,V27,6,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,?,?,44,1,16,0,0,0,8,250.43,403,7,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,?,?,51,0,8,0,0,0,197,157,250,5,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101761,443847548,100162476,AfricanAmerican,Male,[70-80),?,1,3,7,3,MC,?,51,0,16,0,0,0,250.13,291,458,9,NaN,>8,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30
101762,443847782,74694222,AfricanAmerican,Female,[80-90),?,1,4,5,5,MC,?,33,3,18,0,0,1,560,276,787,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,NO
101763,443854148,41088789,Caucasian,Male,[70-80),?,1,1,7,1,MC,?,53,0,9,1,0,0,38,590,296,13,NaN,NaN,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,NO
101764,443857166,31693671,Caucasian,Female,[80-90),?,2,3,7,10,MC,Surgery-General,45,2,21,0,0,1,996,285,998,9,NaN,NaN,No,No,No,No,No,No,Steady,No,No,Steady,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO
101765,443867222,175429310,Caucasian,Male,[70-80),?,1,1,7,6,?,?,13,3,3,0,0,0,530,530,787,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO

In [82]:
df = df.replace("?", np.nan)

In [83]:
df.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),NaN,6,25,1,1,NaN,Pediatrics-Endocrinology,41,0,1,0,0,0,250.83,NaN,NaN,1,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),NaN,1,1,7,3,NaN,NaN,59,0,18,0,0,0,276,250.01,255,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),NaN,1,1,7,2,NaN,NaN,11,5,13,2,0,1,648,250,V27,6,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),NaN,1,1,7,2,NaN,NaN,44,1,16,0,0,0,8,250.43,403,7,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),NaN,1,1,7,1,NaN,NaN,51,0,8,0,0,0,197,157,250,5,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [84]:
df[["age", "weight", "race", "gender"]].isnull().sum()

age           0
weight    98569
race       2273
gender        0
dtype: int64

In [85]:
df = df.dropna(
    subset=["age", "race", "gender"]
)

In [86]:
df.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),NaN,6,25,1,1,NaN,Pediatrics-Endocrinology,41,0,1,0,0,0,250.83,NaN,NaN,1,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),NaN,1,1,7,3,NaN,NaN,59,0,18,0,0,0,276,250.01,255,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),NaN,1,1,7,2,NaN,NaN,11,5,13,2,0,1,648,250,V27,6,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),NaN,1,1,7,2,NaN,NaN,44,1,16,0,0,0,8,250.43,403,7,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),NaN,1,1,7,1,NaN,NaN,51,0,8,0,0,0,197,157,250,5,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [87]:
df[["age", "weight", "race", "gender"]].isnull().sum()

age           0
weight    96434
race          0
gender        0
dtype: int64

In [88]:
df["weight"].value_counts()

weight
[75-100)     1279
[50-75)       861
[100-125)     596
[125-150)     136
[25-50)        93
[0-25)         47
[150-175)      34
[175-200)      10
>200            3
Name: count, dtype: int64

In [89]:
known_weight = df[df["weight"].notna()]

In [90]:
weight_patterns = (
    known_weight
    .groupby(["age", "race", "gender", "weight"])
    .size()
    .reset_index(name="count")
)

In [91]:
weight_patterns.head(20)

        age             race  gender     weight  count
0    [0-10)        Caucasian    Male     [0-25)      2
1    [0-10)        Caucasian    Male    [25-50)      1
2    [0-10)            Other    Male     [0-25)      1
3   [10-20)  AfricanAmerican  Female    [25-50)      1
4   [10-20)  AfricanAmerican  Female    [50-75)      2
5   [10-20)  AfricanAmerican    Male    [25-50)      1
6   [10-20)        Caucasian  Female    [25-50)      2
7   [10-20)        Caucasian  Female    [50-75)      8
8   [10-20)        Caucasian    Male    [50-75)      4
9   [20-30)  AfricanAmerican  Female   [75-100)      2
10  [20-30)  AfricanAmerican    Male    [50-75)      1
11  [20-30)        Caucasian  Female     [0-25)      1
12  [20-30)        Caucasian  Female  [100-125)      6
13  [20-30)        Caucasian  Female  [125-150)      1
14  [20-30)        Caucasian  Female    [50-75)     22
15  [20-30)        Caucasian  Female   [75-100)      8
16  [20-30)        Caucasian    Male  [100-125)      2
17  [20-30)        Caucasian    Male  [150-175)      1
18  [20-30)        Caucasian    Male    [50-75)     15
19  [20-30)        Caucasian    Male   [75-100)      7

In [92]:
weight_lookup = (
    weight_patterns
    .sort_values("count", ascending=False)
    .drop_duplicates(
        subset=["age", "race", "gender"]
    )
)

In [93]:
weight_lookup.head(20)

          age             race  gender    weight  count
146   [70-80)        Caucasian    Male  [75-100)    235
138   [70-80)        Caucasian  Female  [75-100)    200
157   [80-90)        Caucasian  Female   [50-75)    156
121   [60-70)        Caucasian    Male  [75-100)    136
164   [80-90)        Caucasian    Male  [75-100)    132
113   [60-70)        Caucasian  Female  [75-100)    127
83    [50-60)        Caucasian  Female  [75-100)     92
91    [50-60)        Caucasian    Male  [75-100)     76
169  [90-100)        Caucasian  Female   [50-75)     45
62    [40-50)        Caucasian    Male  [75-100)     36
54    [40-50)        Caucasian  Female  [75-100)     32
14    [20-30)        Caucasian  Female   [50-75)     22
31    [30-40)        Caucasian  Female  [75-100)     19
18    [20-30)        Caucasian    Male   [50-75)     15
173  [90-100)        Caucasian    Male  [75-100)     13
35    [30-40)        Caucasian    Male   [50-75)     11
7     [10-20)        Caucasian  Female   [50-75)      8
102   [60-70)  AfricanAmerican    Male   [50-75)      7
127   [70-80)  AfricanAmerican  Female  [75-100)      7
99    [60-70)  AfricanAmerican  Female  [75-100)      7

In [94]:
def fill_weight(age, race, gender):
    
    result = weight_lookup[
        (weight_lookup["age"] == age) &
        (weight_lookup["race"] == race) &
        (weight_lookup["gender"] == gender)
    ]
    
    if len(result) > 0:
        return result.iloc[0]["weight"]
    
    return np.nan

In [97]:
df["weight_filled"] = df.apply(
    lambda row: fill_weight(
        row["age"],
        row["race"],
        row["gender"]
    ) if pd.isna(row["weight"]) else row["weight"],
    axis=1
)

In [98]:
df[["age", "race", "gender", "weight", "weight_filled"]].tail(60)

             age             race  gender     weight weight_filled
101704   [80-90)        Caucasian  Female        NaN       [50-75)
101705   [60-70)        Caucasian    Male        NaN      [75-100)
101706   [70-80)        Caucasian    Male        NaN      [75-100)
101707   [50-60)        Caucasian    Male        NaN      [75-100)
101708   [50-60)        Caucasian  Female        NaN      [75-100)
101709   [60-70)  AfricanAmerican    Male        NaN       [50-75)
101710   [30-40)            Other  Female        NaN           NaN
101711   [80-90)  AfricanAmerican  Female        NaN           NaN
101712   [60-70)        Caucasian  Female        NaN      [75-100)
101713   [40-50)        Caucasian    Male        NaN      [75-100)
101714   [70-80)        Caucasian  Female        NaN      [75-100)
101716   [70-80)            Other    Male        NaN      [75-100)
101717   [50-60)        Caucasian    Male        NaN      [75-100)
101718   [70-80)        Caucasian  Female        NaN      [75-100)
101719   [10-20)        Caucasian    Male        NaN       [50-75)
101720   [50-60)        Caucasian    Male        NaN      [75-100)
101721   [70-80)        Caucasian  Female        NaN      [75-100)
101722   [70-80)        Caucasian  Female        NaN      [75-100)
101723   [60-70)        Caucasian    Male  [150-175)     [150-175)
101724   [60-70)  AfricanAmerican    Male        NaN       [50-75)
101725   [70-80)        Caucasian  Female        NaN      [75-100)
101726   [30-40)         Hispanic    Male        NaN           NaN
101727   [70-80)        Caucasian  Female        NaN      [75-100)
101728   [30-40)        Caucasian  Female        NaN      [75-100)
101729   [70-80)        Caucasian  Female        NaN      [75-100)
101730   [70-80)  AfricanAmerican  Female        NaN      [75-100)
101731   [50-60)        Caucasian    Male        NaN      [75-100)
101733   [80-90)        Caucasian  Female        NaN       [50-75)
101734   [70-80)        Caucasian  Female        NaN      [75-100)
101735   [70-80)        Caucasian    Male        NaN      [75-100)
101736   [60-70)        Caucasian  Female        NaN      [75-100)
101737   [40-50)        Caucasian  Female        NaN      [75-100)
101738   [70-80)        Caucasian    Male        NaN      [75-100)
101739   [70-80)  AfricanAmerican    Male        NaN      [75-100)
101740   [40-50)        Caucasian    Male        NaN      [75-100)
101741  [90-100)  AfricanAmerican    Male        NaN           NaN
101742   [70-80)        Caucasian    Male        NaN      [75-100)
101743   [80-90)        Caucasian    Male        NaN      [75-100)
101744   [80-90)        Caucasian  Female        NaN       [50-75)
101745   [50-60)        Caucasian    Male        NaN      [75-100)
101746   [70-80)        Caucasian    Male        NaN      [75-100)
101747   [70-80)        Caucasian  Female        NaN      [75-100)
101748   [40-50)        Caucasian  Female        NaN      [75-100)
101749   [70-80)        Caucasian  Female        NaN      [75-100)
101750   [80-90)        Caucasian  Female        NaN       [50-75)
101751   [70-80)        Caucasian    Male        NaN      [75-100)
101752   [40-50)            Other  Female        NaN      [75-100)
101753   [40-50)            Other    Male        NaN       [25-50)
101754   [70-80)        Caucasian  Female        NaN      [75-100)
101755   [40-50)            Other  Female        NaN      [75-100)
101756   [60-70)            Other  Female        NaN      [75-100)
101757   [70-80)        Caucasian  Female        NaN      [75-100)
101758   [80-90)        Caucasian  Female        NaN       [50-75)
101759   [80-90)        Caucasian    Male        NaN      [75-100)
101760   [60-70)  AfricanAmerican  Female        NaN      [75-100)
101761   [70-80)  AfricanAmerican    Male        NaN      [75-100)
101762   [80-90)  AfricanAmerican  Female        NaN           NaN
101763   [70-80)        Caucasian    Male        NaN      [75-100)
101764   [80-90)        Caucasian  Female        NaN       [50-75)
101765   [70-80)        Caucasian    Male        NaN      [75-100)

In [99]:
df['weight_filled'].isnull().sum()

np.int64(4402)

In [100]:
known_weight = df[df["weight_filled"].notna()]

In [101]:
weight_patterns = (
    known_weight
    .groupby(["age", "race", "gender", "weight_filled"])
    .size()
    .reset_index(name="count")
)

In [102]:
weight_patterns

          age             race  gender weight_filled  count
0      [0-10)        Caucasian    Male        [0-25)     64
1      [0-10)        Caucasian    Male       [25-50)      1
2      [0-10)            Other    Male        [0-25)      4
3     [10-20)  AfricanAmerican  Female       [25-50)      1
4     [10-20)  AfricanAmerican  Female       [50-75)    129
..        ...              ...     ...           ...    ...
169  [90-100)        Caucasian  Female       [50-75)   1639
170  [90-100)        Caucasian  Female      [75-100)      9
171  [90-100)        Caucasian    Male       [25-50)      2
172  [90-100)        Caucasian    Male       [50-75)     10
173  [90-100)        Caucasian    Male      [75-100)    660

[174 rows x 5 columns]

In [103]:
df.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted,weight_filled
0,2278392,8222157,Caucasian,Female,[0-10),NaN,6,25,1,1,NaN,Pediatrics-Endocrinology,41,0,1,0,0,0,250.83,NaN,NaN,1,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO,NaN
1,149190,55629189,Caucasian,Female,[10-20),NaN,1,1,7,3,NaN,NaN,59,0,18,0,0,0,276,250.01,255,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30,[50-75)
2,64410,86047875,AfricanAmerican,Female,[20-30),NaN,1,1,7,2,NaN,NaN,11,5,13,2,0,1,648,250,V27,6,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO,[75-100)
3,500364,82442376,Caucasian,Male,[30-40),NaN,1,1,7,2,NaN,NaN,44,1,16,0,0,0,8,250.43,403,7,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,[50-75)
4,16680,42519267,Caucasian,Male,[40-50),NaN,1,1,7,1,NaN,NaN,51,0,8,0,0,0,197,157,250,5,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,[75-100)

In [104]:
df=df.dropna(subset=["weight_filled"])

In [105]:
df=df.drop("weight",axis=1)

In [106]:
df

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted,weight_filled
1,149190,55629189,Caucasian,Female,[10-20),1,1,7,3,NaN,NaN,59,0,18,0,0,0,276,250.01,255,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30,[50-75)
2,64410,86047875,AfricanAmerican,Female,[20-30),1,1,7,2,NaN,NaN,11,5,13,2,0,1,648,250,V27,6,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO,[75-100)
3,500364,82442376,Caucasian,Male,[30-40),1,1,7,2,NaN,NaN,44,1,16,0,0,0,8,250.43,403,7,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,[50-75)
4,16680,42519267,Caucasian,Male,[40-50),1,1,7,1,NaN,NaN,51,0,8,0,0,0,197,157,250,5,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,[75-100)
5,35754,82637451,Caucasian,Male,[50-60),2,1,2,3,NaN,NaN,31,6,16,0,0,0,414,411,250,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,[75-100)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101760,443847176,50375628,AfricanAmerican,Female,[60-70),1,1,7,6,DM,NaN,45,1,25,3,1,2,345,438,412,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,[75-100)
101761,443847548,100162476,AfricanAmerican,Male,[70-80),1,3,7,3,MC,NaN,51,0,16,0,0,0,250.13,291,458,9,NaN,>8,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,[75-100)
101763,443854148,41088789,Caucasian,Male,[70-80),1,1,7,1,MC,NaN,53,0,9,1,0,0,38,590,296,13,NaN,NaN,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,NO,[75-100)
101764,443857166,31693671,Caucasian,Female,[80-90),2,3,7,10,MC,Surgery-General,45,2,21,0,0,1,996,285,998,9,NaN,NaN,No,No,No,No,No,No,Steady,No,No,Steady,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,[50-75)
101765,443867222,175429310,Caucasian,Male,[70-80),1,1,7,6,NaN,NaN,13,3,3,0,0,0,530,530,787,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO,[75-100)

In [107]:
df["weight"]=df["weight_filled"]

In [108]:
df

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted,weight_filled,weight
1,149190,55629189,Caucasian,Female,[10-20),1,1,7,3,NaN,NaN,59,0,18,0,0,0,276,250.01,255,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30,[50-75),[50-75)
2,64410,86047875,AfricanAmerican,Female,[20-30),1,1,7,2,NaN,NaN,11,5,13,2,0,1,648,250,V27,6,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO,[75-100),[75-100)
3,500364,82442376,Caucasian,Male,[30-40),1,1,7,2,NaN,NaN,44,1,16,0,0,0,8,250.43,403,7,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,[50-75),[50-75)
4,16680,42519267,Caucasian,Male,[40-50),1,1,7,1,NaN,NaN,51,0,8,0,0,0,197,157,250,5,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,[75-100),[75-100)
5,35754,82637451,Caucasian,Male,[50-60),2,1,2,3,NaN,NaN,31,6,16,0,0,0,414,411,250,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,[75-100),[75-100)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101760,443847176,50375628,AfricanAmerican,Female,[60-70),1,1,7,6,DM,NaN,45,1,25,3,1,2,345,438,412,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,[75-100),[75-100)
101761,443847548,100162476,AfricanAmerican,Male,[70-80),1,3,7,3,MC,NaN,51,0,16,0,0,0,250.13,291,458,9,NaN,>8,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,[75-100),[75-100)
101763,443854148,41088789,Caucasian,Male,[70-80),1,1,7,1,MC,NaN,53,0,9,1,0,0,38,590,296,13,NaN,NaN,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,NO,[75-100),[75-100)
101764,443857166,31693671,Caucasian,Female,[80-90),2,3,7,10,MC,Surgery-General,45,2,21,0,0,1,996,285,998,9,NaN,NaN,No,No,No,No,No,No,Steady,No,No,Steady,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,[50-75),[50-75)
101765,443867222,175429310,Caucasian,Male,[70-80),1,1,7,6,NaN,NaN,13,3,3,0,0,0,530,530,787,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO,[75-100),[75-100)

In [109]:
df.drop("weight_filled",axis=1,inplace=True)

In [110]:
df

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted,weight
1,149190,55629189,Caucasian,Female,[10-20),1,1,7,3,NaN,NaN,59,0,18,0,0,0,276,250.01,255,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30,[50-75)
2,64410,86047875,AfricanAmerican,Female,[20-30),1,1,7,2,NaN,NaN,11,5,13,2,0,1,648,250,V27,6,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO,[75-100)
3,500364,82442376,Caucasian,Male,[30-40),1,1,7,2,NaN,NaN,44,1,16,0,0,0,8,250.43,403,7,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,[50-75)
4,16680,42519267,Caucasian,Male,[40-50),1,1,7,1,NaN,NaN,51,0,8,0,0,0,197,157,250,5,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,[75-100)
5,35754,82637451,Caucasian,Male,[50-60),2,1,2,3,NaN,NaN,31,6,16,0,0,0,414,411,250,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,[75-100)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101760,443847176,50375628,AfricanAmerican,Female,[60-70),1,1,7,6,DM,NaN,45,1,25,3,1,2,345,438,412,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,[75-100)
101761,443847548,100162476,AfricanAmerican,Male,[70-80),1,3,7,3,MC,NaN,51,0,16,0,0,0,250.13,291,458,9,NaN,>8,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,[75-100)
101763,443854148,41088789,Caucasian,Male,[70-80),1,1,7,1,MC,NaN,53,0,9,1,0,0,38,590,296,13,NaN,NaN,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,NO,[75-100)
101764,443857166,31693671,Caucasian,Female,[80-90),2,3,7,10,MC,Surgery-General,45,2,21,0,0,1,996,285,998,9,NaN,NaN,No,No,No,No,No,No,Steady,No,No,Steady,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,[50-75)
101765,443867222,175429310,Caucasian,Male,[70-80),1,1,7,6,NaN,NaN,13,3,3,0,0,0,530,530,787,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO,[75-100)

In [111]:
def convert_age(age):
    
    if pd.isna(age):
        return np.nan
    
    low, high = age[1:-1].split("-")
    
    return int((int(low) + int(high)) / 2)

In [112]:
df["age"] = df["age"].apply(convert_age)

In [113]:
df

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted,weight
1,149190,55629189,Caucasian,Female,15,1,1,7,3,NaN,NaN,59,0,18,0,0,0,276,250.01,255,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30,[50-75)
2,64410,86047875,AfricanAmerican,Female,25,1,1,7,2,NaN,NaN,11,5,13,2,0,1,648,250,V27,6,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO,[75-100)
3,500364,82442376,Caucasian,Male,35,1,1,7,2,NaN,NaN,44,1,16,0,0,0,8,250.43,403,7,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,[50-75)
4,16680,42519267,Caucasian,Male,45,1,1,7,1,NaN,NaN,51,0,8,0,0,0,197,157,250,5,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,[75-100)
5,35754,82637451,Caucasian,Male,55,2,1,2,3,NaN,NaN,31,6,16,0,0,0,414,411,250,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,[75-100)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101760,443847176,50375628,AfricanAmerican,Female,65,1,1,7,6,DM,NaN,45,1,25,3,1,2,345,438,412,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,[75-100)
101761,443847548,100162476,AfricanAmerican,Male,75,1,3,7,3,MC,NaN,51,0,16,0,0,0,250.13,291,458,9,NaN,>8,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,[75-100)
101763,443854148,41088789,Caucasian,Male,75,1,1,7,1,MC,NaN,53,0,9,1,0,0,38,590,296,13,NaN,NaN,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,NO,[75-100)
101764,443857166,31693671,Caucasian,Female,85,2,3,7,10,MC,Surgery-General,45,2,21,0,0,1,996,285,998,9,NaN,NaN,No,No,No,No,No,No,Steady,No,No,Steady,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,[50-75)
101765,443867222,175429310,Caucasian,Male,75,1,1,7,6,NaN,NaN,13,3,3,0,0,0,530,530,787,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO,[75-100)

In [114]:
def convert_weight(weight):
    
    if pd.isna(weight):
        return np.nan
    
    if weight.startswith("["):
        low, high = weight[1:-1].split("-")
        return int((float(low) + float(high)) / 2)
    
    if weight == ">200":
        return 200
    
    return np.nan

In [115]:
df["weight"] = df["weight"].apply(convert_weight)

In [116]:
df

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted,weight
1,149190,55629189,Caucasian,Female,15,1,1,7,3,NaN,NaN,59,0,18,0,0,0,276,250.01,255,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30,62
2,64410,86047875,AfricanAmerican,Female,25,1,1,7,2,NaN,NaN,11,5,13,2,0,1,648,250,V27,6,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO,87
3,500364,82442376,Caucasian,Male,35,1,1,7,2,NaN,NaN,44,1,16,0,0,0,8,250.43,403,7,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,62
4,16680,42519267,Caucasian,Male,45,1,1,7,1,NaN,NaN,51,0,8,0,0,0,197,157,250,5,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,87
5,35754,82637451,Caucasian,Male,55,2,1,2,3,NaN,NaN,31,6,16,0,0,0,414,411,250,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101760,443847176,50375628,AfricanAmerican,Female,65,1,1,7,6,DM,NaN,45,1,25,3,1,2,345,438,412,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,87
101761,443847548,100162476,AfricanAmerican,Male,75,1,3,7,3,MC,NaN,51,0,16,0,0,0,250.13,291,458,9,NaN,>8,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,87
101763,443854148,41088789,Caucasian,Male,75,1,1,7,1,MC,NaN,53,0,9,1,0,0,38,590,296,13,NaN,NaN,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,NO,87
101764,443857166,31693671,Caucasian,Female,85,2,3,7,10,MC,Surgery-General,45,2,21,0,0,1,996,285,998,9,NaN,NaN,No,No,No,No,No,No,Steady,No,No,Steady,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,62
101765,443867222,175429310,Caucasian,Male,75,1,1,7,6,NaN,NaN,13,3,3,0,0,0,530,530,787,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO,87

In [117]:
df['payer_code'].unique()

array([nan, 'MC', 'MD', 'HM', 'UN', 'BC', 'SP', 'CP', 'SI', 'DM', 'CM',
       'CH', 'PO', 'WC', 'OT', 'OG', 'MP'], dtype=object)

In [118]:
df['payer_code'].isnull().sum()

np.int64(37681)

In [119]:
df.columns.to_list()

['encounter_id',
 'patient_nbr',
 'race',
 'gender',
 'age',
 'admission_type_id',
 'discharge_disposition_id',
 'admission_source_id',
 'time_in_hospital',
 'payer_code',
 'medical_specialty',
 'num_lab_procedures',
 'num_procedures',
 'num_medications',
 'number_outpatient',
 'number_emergency',
 'number_inpatient',
 'diag_1',
 'diag_2',
 'diag_3',
 'number_diagnoses',
 'max_glu_serum',
 'A1Cresult',
 'metformin',
 'repaglinide',
 'nateglinide',
 'chlorpropamide',
 'glimepiride',
 'acetohexamide',
 'glipizide',
 'glyburide',
 'tolbutamide',
 'pioglitazone',
 'rosiglitazone',
 'acarbose',
 'miglitol',
 'troglitazone',
 'tolazamide',
 'examide',
 'citoglipton',
 'insulin',
 'glyburide-metformin',
 'glipizide-metformin',
 'glimepiride-pioglitazone',
 'metformin-rosiglitazone',
 'metformin-pioglitazone',
 'change',
 'diabetesMed',
 'readmitted',
 'weight']

In [120]:
df.drop("payer_code",axis=1,inplace=True)

In [121]:
df

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted,weight
1,149190,55629189,Caucasian,Female,15,1,1,7,3,NaN,59,0,18,0,0,0,276,250.01,255,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30,62
2,64410,86047875,AfricanAmerican,Female,25,1,1,7,2,NaN,11,5,13,2,0,1,648,250,V27,6,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO,87
3,500364,82442376,Caucasian,Male,35,1,1,7,2,NaN,44,1,16,0,0,0,8,250.43,403,7,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,62
4,16680,42519267,Caucasian,Male,45,1,1,7,1,NaN,51,0,8,0,0,0,197,157,250,5,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,87
5,35754,82637451,Caucasian,Male,55,2,1,2,3,NaN,31,6,16,0,0,0,414,411,250,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101760,443847176,50375628,AfricanAmerican,Female,65,1,1,7,6,NaN,45,1,25,3,1,2,345,438,412,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,87
101761,443847548,100162476,AfricanAmerican,Male,75,1,3,7,3,NaN,51,0,16,0,0,0,250.13,291,458,9,NaN,>8,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,87
101763,443854148,41088789,Caucasian,Male,75,1,1,7,1,NaN,53,0,9,1,0,0,38,590,296,13,NaN,NaN,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,NO,87
101764,443857166,31693671,Caucasian,Female,85,2,3,7,10,Surgery-General,45,2,21,0,0,1,996,285,998,9,NaN,NaN,No,No,No,No,No,No,Steady,No,No,Steady,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,62
101765,443867222,175429310,Caucasian,Male,75,1,1,7,6,NaN,13,3,3,0,0,0,530,530,787,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO,87

In [122]:
df["medical_specialty"].unique()

array([nan, 'InternalMedicine', 'Family/GeneralPractice', 'Cardiology',
       'Surgery-General', 'Orthopedics', 'Gastroenterology',
       'Surgery-Cardiovascular/Thoracic', 'Nephrology',
       'Orthopedics-Reconstructive', 'Psychiatry', 'Emergency/Trauma',
       'Pulmonology', 'Surgery-Neuro',
       'Obsterics&Gynecology-GynecologicOnco', 'ObstetricsandGynecology',
       'Pediatrics', 'Pediatrics-Endocrinology', 'Otolaryngology',
       'Surgery-Colon&Rectal', 'Endocrinology', 'Hematology/Oncology',
       'Urology', 'Pediatrics-CriticalCare',
       'Psychiatry-Child/Adolescent', 'Pediatrics-Pulmonology',
       'Anesthesiology-Pediatric', 'Radiology',
       'Pediatrics-Hematology-Oncology', 'Psychology', 'Neurology',
       'Podiatry', 'Gynecology', 'Oncology', 'Pediatrics-Neurology',
       'Surgery-Plastic', 'Surgery-Thoracic',
       'Surgery-PlasticwithinHeadandNeck', 'Ophthalmology',
       'Pediatrics-EmergencyMedicine',
       'PhysicalMedicineandRehabilitation', 'InfectiousDiseases',
       'Anesthesiology', 'Surgery-Pediatric', 'Rheumatology',
       'AllergyandImmunology', 'Surgery-Maxillofacial',
       'Pediatrics-InfectiousDiseases', 'Pediatrics-AllergyandImmunology',
       'Dentistry', 'Surgeon', 'Surgery-Vascular', 'Osteopath',
       'Psychiatry-Addictive', 'Surgery-Cardiovascular',
       'PhysicianNotFound', 'Hematology', 'Proctology', 'Obstetrics',
       'SurgicalSpecialty', 'Radiologist', 'Pathology', 'Dermatology',
       'SportsMedicine', 'Hospitalist', 'OutreachServices',
       'Cardiology-Pediatric', 'Perinatology', 'Neurophysiology',
       'Endocrinology-Metabolism', 'DCPTEAM', 'Resident'], dtype=object)

In [123]:
df["medical_specialty"].isnull().sum()

np.int64(46922)

In [124]:
df["num_lab_procedures"].isnull().sum()

np.int64(0)

In [125]:
df["num_procedures"].isnull().sum()

np.int64(0)

In [126]:
df["num_medications"].isnull().sum()

np.int64(0)

In [127]:
df["number_outpatient"].isnull().sum()

np.int64(0)

In [128]:
df.isnull().sum()

encounter_id                    0
patient_nbr                     0
race                            0
gender                          0
age                             0
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
medical_specialty           46922
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                         14
diag_2                        295
diag_3                       1222
number_diagnoses                0
max_glu_serum               90042
A1Cresult                   79364
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
weight                          0
dtype: int64

In [129]:
df

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted,weight
1,149190,55629189,Caucasian,Female,15,1,1,7,3,NaN,59,0,18,0,0,0,276,250.01,255,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30,62
2,64410,86047875,AfricanAmerican,Female,25,1,1,7,2,NaN,11,5,13,2,0,1,648,250,V27,6,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO,87
3,500364,82442376,Caucasian,Male,35,1,1,7,2,NaN,44,1,16,0,0,0,8,250.43,403,7,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,62
4,16680,42519267,Caucasian,Male,45,1,1,7,1,NaN,51,0,8,0,0,0,197,157,250,5,NaN,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,87
5,35754,82637451,Caucasian,Male,55,2,1,2,3,NaN,31,6,16,0,0,0,414,411,250,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101760,443847176,50375628,AfricanAmerican,Female,65,1,1,7,6,NaN,45,1,25,3,1,2,345,438,412,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,87
101761,443847548,100162476,AfricanAmerican,Male,75,1,3,7,3,NaN,51,0,16,0,0,0,250.13,291,458,9,NaN,>8,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,87
101763,443854148,41088789,Caucasian,Male,75,1,1,7,1,NaN,53,0,9,1,0,0,38,590,296,13,NaN,NaN,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,NO,87
101764,443857166,31693671,Caucasian,Female,85,2,3,7,10,Surgery-General,45,2,21,0,0,1,996,285,998,9,NaN,NaN,No,No,No,No,No,No,Steady,No,No,Steady,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,62
101765,443867222,175429310,Caucasian,Male,75,1,1,7,6,NaN,13,3,3,0,0,0,530,530,787,9,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO,87

In [130]:
df[df["max_glu_serum"].notna()]

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted,weight
133,2265486,44279478,Caucasian,Male,75,6,1,1,6,NaN,55,1,13,0,0,0,574,250.02,276,3,>300,NaN,No,No,No,No,No,No,Up,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Ch,Yes,NO,87
135,2292606,53848278,AfricanAmerican,Female,75,6,1,7,13,NaN,75,0,16,0,0,0,491,250.03,999,5,>300,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,>30,87
142,2309268,77475465,Caucasian,Female,85,6,1,7,9,NaN,42,0,9,0,0,0,682,428,250.03,5,Norm,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,62
144,2311404,95586993,Caucasian,Female,95,6,3,7,11,NaN,70,1,23,0,0,0,560,997,276,5,Norm,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO,62
153,2430276,69318126,Caucasian,Male,75,6,1,7,7,NaN,82,2,21,0,0,0,427,228,529,5,Norm,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO,87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101088,434900486,126428594,AfricanAmerican,Male,45,6,7,7,2,InternalMedicine,60,0,4,0,0,0,250.22,276,276,6,>300,>8,Steady,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,87
101094,434911802,91776843,Caucasian,Male,55,1,1,7,11,NaN,48,2,35,0,0,8,491,585,780,9,>300,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,>30,87
101100,434928416,59178681,Caucasian,Female,75,6,6,7,2,InternalMedicine,61,0,8,0,0,4,250.8,780,464,3,Norm,NaN,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,>30,87
101221,436664606,81493128,Caucasian,Male,75,6,1,7,9,InternalMedicine,94,0,34,0,0,0,428,707,459,6,Norm,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,>30,87
101413,439020524,108070092,Caucasian,Female,75,6,6,7,4,InternalMedicine,49,3,31,0,0,0,410,266,250,6,>200,NaN,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,87

In [131]:
df["A1Cresult"].isna().mean() * 100

np.float64(83.46110567771923)

In [132]:
df["A1Cresult"].value_counts(dropna=False)

A1Cresult
NaN     79364
>8       7523
Norm     4658
>7       3546
Name: count, dtype: int64

In [133]:
df.drop("A1Cresult", axis=1, inplace=True)

In [134]:
df.drop("max_glu_serum", axis=1, inplace=True)

In [135]:
df

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted,weight
1,149190,55629189,Caucasian,Female,15,1,1,7,3,NaN,59,0,18,0,0,0,276,250.01,255,9,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30,62
2,64410,86047875,AfricanAmerican,Female,25,1,1,7,2,NaN,11,5,13,2,0,1,648,250,V27,6,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO,87
3,500364,82442376,Caucasian,Male,35,1,1,7,2,NaN,44,1,16,0,0,0,8,250.43,403,7,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,62
4,16680,42519267,Caucasian,Male,45,1,1,7,1,NaN,51,0,8,0,0,0,197,157,250,5,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,87
5,35754,82637451,Caucasian,Male,55,2,1,2,3,NaN,31,6,16,0,0,0,414,411,250,9,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101760,443847176,50375628,AfricanAmerican,Female,65,1,1,7,6,NaN,45,1,25,3,1,2,345,438,412,9,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,87
101761,443847548,100162476,AfricanAmerican,Male,75,1,3,7,3,NaN,51,0,16,0,0,0,250.13,291,458,9,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,87
101763,443854148,41088789,Caucasian,Male,75,1,1,7,1,NaN,53,0,9,1,0,0,38,590,296,13,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,NO,87
101764,443857166,31693671,Caucasian,Female,85,2,3,7,10,Surgery-General,45,2,21,0,0,1,996,285,998,9,No,No,No,No,No,No,Steady,No,No,Steady,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,62
101765,443867222,175429310,Caucasian,Male,75,1,1,7,6,NaN,13,3,3,0,0,0,530,530,787,9,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO,87

In [136]:
df.isnull().sum()

encounter_id                    0
patient_nbr                     0
race                            0
gender                          0
age                             0
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
medical_specialty           46922
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                         14
diag_2                        295
diag_3                       1222
number_diagnoses                0
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
weight                          0
dtype: int64

In [137]:
df['diag_3'].unique()

array(['255', 'V27', '403', '250', 'V45', '38', '486', '996', '197',
       '250.6', '427', '627', '414', '416', '582', 'V43', '250.01', '263',
       '250.42', '276', '482', '401', '250.41', '585', '781', '278',
       '998', '428', '568', '682', '250.02', '305', '707', '496', '599',
       nan, '424', '518', '553', '794', '411', 'V42', '531', '511', '490',
       '562', '250.8', '250.7', '250.52', '784', '491', '581', '420',
       '724', '730', '789', '131', '250.82', '999', '41', '493', '250.03',
       '753', '786', '529', 'E888', '425', '595', '303', '560', '711',
       '8', '492', '332', '296', '438', '362', '250.4', '654', '244',
       'V70', '737', '625', '250.51', 'V10', '810', '280', '440', '785',
       '569', '272', '997', '250.43', '918', '584', '788', '426', '722',
       '250.92', '196', '461', '535', '787', '891', '284', '458', '648',
       '780', '182', '285', '593', '413', '664', '564', '201', '356',
       'V15', '292', '782', '715', '473', '714', 'E932', '357', '348',
       '294', '250.23', '459', 'E878', '437', '733', '507', '525',
       '250.53', '397', '572', '805', '453', '331', '736', '591', '576',
       '465', '533', '703', '349', '315', '658', '608', '578', '716',
       '300', '282', '571', '536', '596', '287', '644', 'V11', '558',
       'E885', '162', '198', '218', '412', '396', 'V14', '570', '433',
       'E934', '288', '577', '443', '729', '836', '295', '799', '281',
       '304', '153', '410', '616', '250.83', '601', '291', '75', '512',
       '660', '250.5', '598', '337', '574', '653', 'V58', '311', '415',
       '386', '602', '790', '112', '873', '620', '436', '70', '54', '155',
       '138', '663', '530', '710', '42', '342', '250.91', 'E884', '515',
       '307', '704', '728', '731', '583', '238', '441', '293', '573',
       '532', '290', '402', '594', '319', '250.13', '519', '346', '380',
       '135', '642', '698', '924', '905', 'E933', '555', '309', 'E879',
       '286', '565', '752', '580', '681', '446', '444', '344', '455',
       '252', '35', '813', '394', '301', '258', 'V17', '802', '435',
       '746', 'V12', '709', '881', 'E935', '139', '250.81', '718', '365',
       '202', '334', '185', '398', 'V44', '517', 'E849', '614', '466',
       '626', '250.9', '368', '605', '883', '289', '478', '617', '429',
       '442', 'V25', '866', '610', '557', '959', 'E942', '94', '920',
       '345', '313', '379', '79', '516', '586', '821', '600', '242',
       '373', '592', 'V64', '487', '253', '706', 'E947', '117', '340',
       'E950', '656', 'E949', '590', 'V09', '250.22', '934', '694', '203',
       '250.93', '995', '726', '923', '958', '275', 'E929', '211', 'V66',
       '199', '665', '53', '522', '791', '890', '456', 'E938', 'E816',
       '122', '721', 'V65', '136', '480', '423', 'E920', '793', '647',
       '537', '575', '351', '845', '336', '274', '719', '404', '945',
       '434', '494', '157', '208', '174', 'V57', '812', '734', '150',
       'V23', '447', '692', '228', 'V16', '756', '405', 'E928', '382',
       '552', '389', '240', '454', '366', '907', '270', '310', '266',
       '387', 'E931', '783', '245', '607', '355', 'E930', '705', '372',
       '369', '611', '283', 'V46', '110', '867', 'E956', '251', '250.2',
       '820', '712', '695', '567', '343', '723', 'V08', '273', '623',
       '807', '823', '618', '451', '495', '701', 'V53', '314', '472',
       'E945', '11', '189', '534', '354', '333', 'V54', '277', '659',
       'E939', '708', '250.12', '452', '655', '816', '670', '621', '34',
       '246', '953', 'E817', '646', '378', '78', '298', '840', '641',
       '521', '745', '619', '792', '912', '506', 'E904', '151', 'E980',
       '383', '204', '696', '566', '727', '47', 'E943', '358', '191',
       '965', '921', '432', '27', 'E861', '758', '477', '524', '751',
       '652', 'V18', '556', '188', '825', '919', '732', 'E870', '908',
       '951', '962', '685', 'E944', '527', '341', '865', '693', '250.1',
       'V49', '860', '323', '579', '508', '969', '205', '462', 'E880',
       '680', '697', '826', '200', '457', '717', '738', '742', '735',
       '235', '308', '528', '725', '241', '824', '464', '260', '239',
       '892', '261', 'E883', '943', '744', 'E936', '796', '318', '967',
       '350', '854', 'E905', '741', 'E941', '882', '170', '643', '317',
       '759', '909', '279', 'V22', '831', '713', '180', '801', '359',
       '501', '335', '250.11', '306', '811', '690', 'V02', '214', '847',
       '543', 'V63', '906', '842', '686', '445', 'V55', '808', '861',
       'E852', '220', 'E887', 'E858', '915', '970', '256', '747', '395',
       '243', '815', '481', '5', 'E927', '297', '299', '851', '864',
       '922', '384', 'E876', '225', '158', 'E937', '871', '88', 'E917',
       'E812', 'V62', 'E924', '233', 'V72', '172', '421', '852', 'E819',
       '972', '259', '916', '956', '3', 'E965', '173', '193', '154',
       '347', '862', '250.3', '987', '470', '262', 'E855', '161', '115',
       '179', '910', '312', '17', '460', '265', '66', '163', 'V60', '870',
       '661', 'E906', '514', '944', '844', '417', '152', '183', '991',
       '917', '216', '9', '385', '360', '797', '935', '510', '485', '227',
       '250.21', 'E919', '872', '377', '195', '588', '431', '597', '933',
       '171', '884', '156', '868', '483', 'E815', '542', 'V61', '853',
       'E850', 'E881', 'E882', 'E822', '192', '754', '327', '523', '500',
       'V85', '992', '657', '604', '684', '603', '850', 'E826', '550',
       '913', 'E916', '376', '755', '361', '186', '720', '250.31', '674',
       '911', '374', 'E813', '226', '365.44', 'E818', '146', '955',
       'E894', '475', 'V13', '880', '930', 'E915', '381', '353', '795',
       '893', 'V01', 'E853', '863', '132', '540', 'E828', '430', '800',
       'E865', '148', 'E946', '822', '879', '848', 'V86', 'V03', '338',
       '989', '388', '111', '123', '757', 'E901', '141', '268', 'E892',
       '649', '702', '948', '223', '484', 'E886', '838', '928', '236',
       '624', '837', 'E987', 'V07', '841', '622', 'E912', '966', 'E955',
       'V06', 'E864', '217', '877', '391', 'E825', '952', '814', '7',
       '669', '875', 'E900', '215', '538', '980', '448', '175', '49',
       '876', '57', '271', '942', '14', '750', '370', '671', '971'],
      dtype=object)

In [138]:
df['diag_2'].unique()

array(['250.01', '250', '250.43', '157', '411', '492', '427', '198',
       '403', '288', '998', '507', '174', '425', '401', '715', '496',
       '428', '585', '250.02', '410', '999', '996', '135', '244', '41',
       '571', '276', '997', '599', '424', '491', '553', '707', '286',
       '440', '493', '70', 'V45', '250.03', '357', nan, '511', '196',
       '396', '197', '414', '250.52', '577', '535', '413', '53', '780',
       '518', '566', '250.6', '867', '285', '486', 'V15', '8', '788',
       '340', '574', '581', '228', '530', '250.82', '786', '294', '567',
       '785', '512', '305', '250.51', '280', '648', '560', 'V10', '578',
       '277', '781', '250.42', '278', '426', '584', '402', '153', '272',
       '733', '34', '881', '203', '250.41', '250.13', '729', '293', '245',
       '250.12', '787', '342', '573', '626', '303', '250.53', '458',
       '710', '415', 'V42', '284', '569', '759', '112', '292', '435',
       '682', '290', '250.93', '642', '536', '398', '444', '319', 'E878',
       '446', 'V44', '242', '38', '250.7', '300', '562', '162', '287',
       '447', '789', '790', '591', '200', '154', '304', '117', '847',
       '852', '250.83', '250.11', '575', '416', '412', '515', '482',
       '382', '456', 'V65', '572', '283', '78', '250.81', '576', '432',
       '295', 'V12', '204', '466', '721', '434', '590', '271', '813',
       '368', '227', '783', '250.5', '258', '253', '309', '250.91', '519',
       '333', '250.92', '250.4', '179', '420', '345', '433', '661', '537',
       '205', '722', '405', '437', '784', '714', '211', 'E812', '263',
       '202', '397', '250.23', 'E932', '201', '301', '723', '614', '568',
       '861', '711', 'V57', '724', '189', '558', '297', '255', '453',
       'E888', '730', '354', '462', '150', '451', '738', 'E939', '805',
       'V43', '155', '910', '218', '358', '220', 'E937', '583', '958',
       '564', '436', '250.22', '620', '621', '331', '617', '596', '314',
       '378', '250.8', '625', '478', '731', '172', '404', '681', '794',
       '470', '279', '281', '531', '443', '799', '337', '311', '719',
       'E944', '423', 'E870', '465', 'E849', '782', '481', '480', 'V23',
       '199', '79', '438', '348', '42', 'E950', '473', '627', '54', '490',
       '317', '332', '508', '369', '600', '349', '485', '208', '922',
       '431', '296', 'E934', '753', 'E935', '386', '728', '607', 'E915',
       '344', '289', '191', '873', '850', '611', '377', '616', 'V17',
       '136', '933', 'E885', '860', '441', '513', '603', '484', '223',
       'V72', '291', '151', 'V58', '550', '510', '891', '185', '592',
       '138', '598', '336', '362', '217', '825', '298', '821', 'E880',
       '343', '429', '716', 'E879', '579', '225', '250.9', 'V49', '696',
       '658', '969', '275', '595', '618', '250.1', '601', '704', '808',
       'E890', '920', '380', '570', 'E817', '359', '812', '274', 'V14',
       '324', '758', 'V66', '911', 'E931', 'E924', '792', '727', 'V46',
       '394', '532', 'V64', '557', '593', '864', '718', '459', '726',
       'E942', '807', '604', '924', '820', '580', '273', '241', '282',
       '824', 'V61', '646', '701', '736', '565', '250.2', 'E947', '452',
       '872', '905', 'E930', '921', '131', '389', '421', '705', '494',
       '752', '623', '9', '959', '365', '967', 'E858', '40', '691', '5',
       '814', '746', '250.31', '556', '680', '745', '351', '306', '695',
       '552', '346', '918', '882', '947', '520', '188', '31', '356',
       '737', 'V08', '322', '182', '517', '974', 'E929', 'V53', '912',
       '252', '608', '516', 'E933', '94', '702', '923', '594', '647',
       '111', '934', '430', '487', '709', '796', '156', '977', '791',
       '915', '756', 'V18', '455', '840', '341', '259', '693', '725',
       'V62', '528', '683', '953', '457', '501', 'E900', 'V09', '522',
       '919', '461', '506', '816', '483', 'E936', '802', '335', 'V54',
       '320', '945', '906', '239', '454', '826', '823', 'E941', '226',
       '795', '684', '844', '250.33', '308', '615', '588', '712', '663',
       '706', '833', '713', '533', 'E884', '233', '586', '214', '555',
       '717', '755', 'E928', '742', '869', '962', '110', 'V11', '543',
       '870', '913', '810', '965', '907', '908', '152', '845', '442',
       '751', '323', '472', '464', '686', '540', '250.32', '251', '811',
       '652', '851', '422', '815', '325', '463', '992', '692', '995',
       '521', '917', '524', '741', '916', '193', 'E813', '173', '238',
       '137', '514', '312', '837', '355', '622', '475', '500', '754',
       '261', '801', '868', '307', '968', '381', '11', '250.21', '694',
       '610', '734', 'E814', '310', '130', '246', '892', '846', '634',
       '75', 'E927', 'E905', '183', '379', 'E917', '163', 'E868', '495',
       '747', '372', '989', 'E854', '240', '832', '605', '602', '644',
       'V16', '35', 'V70', '376', '266', 'E918', '477', '656', '46',
       '883', '171', 'V13', '698', '373', '842', 'E850', '800', '269',
       '664', 'E887', '952', '164', 'E881', '527', '685', '366', '836',
       '27', 'V63', '793', '232', '990', '52', '831', '327', '542', '806',
       '972', '862', 'E829', 'E919', '448', 'E916', '963', '316', '909',
       '645', '347', '374', 'V85', 'V02', '748', '256', '186', '866',
       '96', '395', '262', '865', 'E819', '654', '994', '299', '318',
       'E826', '879', '641', '822', '145', '797', '353', 'E938', 'E816',
       '948', '987', '99', '192', '250.3', 'E906', '534', '115', 'E818',
       'E980', '360', '338', '871', '750', '212', '302', '955', '141',
       '88', 'V25', '215', '350', 'V50', 'V03', 'E853', 'E968', 'E882',
       '140', '703', '991', '893', 'E821', '383', 'V69', '670', 'V55',
       '388', '268', '352', '114', '853', '260', '7', '880', 'V86', '619',
       '659', '180', 'E945', '523', '863', '649', '270', '460', '942',
       '364', '66', 'E883', '123', '884', 'V60', '474', '843'],
      dtype=object)

In [139]:
df['diag_1'].unique()

array(['276', '648', '8', '197', '414', '428', '398', '434', '250.7',
       '157', '518', '999', '410', '682', '402', 'V57', '189', '786',
       '427', '996', '277', '584', '462', '473', '411', '174', '486',
       '998', '511', '432', '626', '295', '196', '250.6', '182', '845',
       '808', '250.4', '722', '403', '250.11', '784', '707', '440', '151',
       '715', '997', '198', '564', '38', '590', '578', '250.32', '433',
       '569', '185', '536', '255', '250.13', '599', '558', '574', '491',
       '560', '244', '250.03', '577', '730', '188', '824', '250.8', '332',
       '562', '291', '296', '510', '401', '263', '438', '70', '250.02',
       '493', '642', '571', '738', '593', '618', '807', '456', '446',
       '572', '575', '250.41', '820', '515', '780', '250.22', '995',
       '235', '250.82', '721', '787', '556', '162', '724', '282',
       '250.83', '514', 'V55', '281', '250.33', '530', '466', '435',
       '250.12', 'V53', '789', '566', '822', '191', '557', '733', '711',
       '482', '202', '280', '553', '154', '441', '250.81', '349', nan,
       '962', '592', '386', '156', '200', '728', '459', '426', '507',
       '607', '337', '82', '531', '812', '225', '596', '288', 'V58',
       '656', '573', '492', '220', '516', '210', '922', '286', '958',
       '661', '969', '250.93', '227', '112', '404', '823', '532', '416',
       '346', '535', '453', '250', '595', '211', '303', '250.01', '852',
       '218', '540', '457', '285', '431', '340', '550', '351', '601',
       '723', '555', '153', '443', '380', '204', '424', '241', '358',
       '694', '345', '681', '447', '290', '158', '579', '436', '335',
       '309', '654', '805', '799', '292', '455', '250.42', '183', '78',
       '851', '458', '586', '311', '54', '892', '305', '293', '415',
       '591', '794', '803', '429', '278', '658', '598', '729', '585',
       '444', '604', '727', '214', '552', '284', '680', '708', '41',
       '644', '481', '821', '413', '437', '968', '756', '632', '782',
       '359', '275', '423', '512', '781', '420', '368', '79', '522',
       '737', '294', '825', '135', '304', '320', '250.31', '669', '868',
       '496', '250.43', '826', '567', '3', '203', '53', '251', '565',
       '495', '49', '250.1', '297', '663', '576', '355', '850', '287',
       '331', '250.2', '611', '348', '350', '726', '537', '620', '180',
       '366', '783', '11', '716', '250.3', '199', '464', '580', '836',
       '664', '283', '966', '289', '965', '184', '480', '608', '333',
       '972', '212', '117', '788', '625', '924', '959', '621', '238',
       '785', '714', '942', '250.23', '710', '47', '933', '508', '478',
       '844', '7', '233', '42', '397', '395', '201', '421', '253',
       '250.92', '600', '494', '977', '39', '659', '312', '614', '647',
       '652', '646', '274', '861', '425', '527', '451', '485', '217',
       '250.53', '442', '970', '160', '322', '581', '475', '623', '374',
       '582', '568', '237', '376', '150', '461', '913', '226', '617',
       '987', '641', '298', '790', '336', '362', '228', '513', '383',
       '746', '353', '911', '506', '873', '155', '860', '465', '534',
       '802', '141', 'V45', '310', '341', '242', '719', '736', '533',
       '616', '301', 'V66', '5', '989', '230', '300', '853', '871', '570',
       '848', '463', '9', '934', '250.21', '361', '594', '810', '643',
       '430', '528', '205', '791', '983', '992', '519', '490', '396',
       '172', '171', '622', '306', '863', '864', '474', '660', '759',
       '356', '239', '840', '634', '967', '551', '695', '187', '732',
       '747', '323', '308', '370', '252', '801', '152', '846', '193',
       '164', '718', '48', '266', '720', '94', '161', '344', '797', '813',
       '170', '878', '904', 'V56', '882', '843', '709', '973', '454',
       '686', '939', '487', '229', '991', '250.5', '483', '357', '692',
       '796', '693', '935', '936', '800', 'V26', '261', '307', '262',
       '250.9', '831', '145', '388', '223', 'V71', '839', '685', 'V54',
       '655', '35', '920', '34', '179', '964', '136', '324', '389', '815',
       '334', '143', '526', '588', '192', 'V67', '394', '917', '88',
       '219', '325', '501', '792', '717', '994', '990', '793', '207',
       '195', '373', '847', '827', '31', '891', '814', 'V60', '703',
       '865', '352', '627', '378', '342', '886', '369', '745', '705',
       '816', '541', '610', '633', '640', '173', '751', '753', '835',
       '379', '445', '272', '945', '619', '881', '250.52', '866', '405',
       '916', '215', '893', '75', '906', '897', '725', '867', '115',
       '734', '521', '674', '470', '834', '146', '696', '524', '980',
       '691', '384', '142', '879', '250.51', '246', '208', '448', '955',
       '653', '149', '245', '735', '883', '854', '952', '838', '194',
       '163', '216', '147', '354', '27', '477', '318', '880', '921',
       '890', '377', '471', '986', '175', '602', '250.91', '982', '382',
       '683', '706', '375', '417', '131', '347', '385', '148', '862',
       '61', '817', '914', '360', '684', '314', 'V63', '36', '57', '240',
       '915', '971', '795', '988', '452', '963', '327', '731', '842',
       'V25', '645', '665', '110', '944', '603', '923', '412', '363',
       '957', '976', '698', '299', '700', '273', '974', '97', '529', '66',
       '98', '605', '941', '806', '84', '271', '837', '657', '895', '338',
       '523', '542', '114', '543', '372', 'V70', '583', 'V07', '422',
       '615', '279', '500', '928', '919', '236', '381', '804', '704',
       '23', '58', '649', '875', '832', '133', '975', '833', '690', '10',
       '52', 'V51'], dtype=object)

In [140]:
df.isnull().sum()

encounter_id                    0
patient_nbr                     0
race                            0
gender                          0
age                             0
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
medical_specialty           46922
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                         14
diag_2                        295
diag_3                       1222
number_diagnoses                0
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
weight                          0
dtype: int64

In [141]:
df.dropna(subset=["diag_1","diag_2","diag_3"], inplace=True)

In [142]:
df

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted,weight
1,149190,55629189,Caucasian,Female,15,1,1,7,3,NaN,59,0,18,0,0,0,276,250.01,255,9,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30,62
2,64410,86047875,AfricanAmerican,Female,25,1,1,7,2,NaN,11,5,13,2,0,1,648,250,V27,6,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO,87
3,500364,82442376,Caucasian,Male,35,1,1,7,2,NaN,44,1,16,0,0,0,8,250.43,403,7,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,62
4,16680,42519267,Caucasian,Male,45,1,1,7,1,NaN,51,0,8,0,0,0,197,157,250,5,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,87
5,35754,82637451,Caucasian,Male,55,2,1,2,3,NaN,31,6,16,0,0,0,414,411,250,9,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101760,443847176,50375628,AfricanAmerican,Female,65,1,1,7,6,NaN,45,1,25,3,1,2,345,438,412,9,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,87
101761,443847548,100162476,AfricanAmerican,Male,75,1,3,7,3,NaN,51,0,16,0,0,0,250.13,291,458,9,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,87
101763,443854148,41088789,Caucasian,Male,75,1,1,7,1,NaN,53,0,9,1,0,0,38,590,296,13,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,NO,87
101764,443857166,31693671,Caucasian,Female,85,2,3,7,10,Surgery-General,45,2,21,0,0,1,996,285,998,9,No,No,No,No,No,No,Steady,No,No,Steady,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,62
101765,443867222,175429310,Caucasian,Male,75,1,1,7,6,NaN,13,3,3,0,0,0,530,530,787,9,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO,87

In [143]:
df.isnull().sum()

encounter_id                    0
patient_nbr                     0
race                            0
gender                          0
age                             0
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
medical_specialty           46505
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                          0
diag_2                          0
diag_3                          0
number_diagnoses                0
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
weight                          0
dtype: int64

In [144]:
df["medical_specialty"] = df["medical_specialty"].fillna("Unknown")

In [145]:
df

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted,weight
1,149190,55629189,Caucasian,Female,15,1,1,7,3,Unknown,59,0,18,0,0,0,276,250.01,255,9,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30,62
2,64410,86047875,AfricanAmerican,Female,25,1,1,7,2,Unknown,11,5,13,2,0,1,648,250,V27,6,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO,87
3,500364,82442376,Caucasian,Male,35,1,1,7,2,Unknown,44,1,16,0,0,0,8,250.43,403,7,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,62
4,16680,42519267,Caucasian,Male,45,1,1,7,1,Unknown,51,0,8,0,0,0,197,157,250,5,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,87
5,35754,82637451,Caucasian,Male,55,2,1,2,3,Unknown,31,6,16,0,0,0,414,411,250,9,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101760,443847176,50375628,AfricanAmerican,Female,65,1,1,7,6,Unknown,45,1,25,3,1,2,345,438,412,9,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,87
101761,443847548,100162476,AfricanAmerican,Male,75,1,3,7,3,Unknown,51,0,16,0,0,0,250.13,291,458,9,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,87
101763,443854148,41088789,Caucasian,Male,75,1,1,7,1,Unknown,53,0,9,1,0,0,38,590,296,13,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,NO,87
101764,443857166,31693671,Caucasian,Female,85,2,3,7,10,Surgery-General,45,2,21,0,0,1,996,285,998,9,No,No,No,No,No,No,Steady,No,No,Steady,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,62
101765,443867222,175429310,Caucasian,Male,75,1,1,7,6,Unknown,13,3,3,0,0,0,530,530,787,9,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO,87

In [146]:
df.drop("encounter_id", axis=1, inplace=True)

In [147]:
df.drop("patient_nbr", axis=1, inplace=True)

In [148]:
df

,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_2,diag_3,number_diagnoses,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,glyburide,tolbutamide,pioglitazone,rosiglitazone,acarbose,miglitol,troglitazone,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted,weight
1,Caucasian,Female,15,1,1,7,3,Unknown,59,0,18,0,0,0,276,250.01,255,9,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,>30,62
2,AfricanAmerican,Female,25,1,1,7,2,Unknown,11,5,13,2,0,1,648,250,V27,6,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,NO,87
3,Caucasian,Male,35,1,1,7,2,Unknown,44,1,16,0,0,0,8,250.43,403,7,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,62
4,Caucasian,Male,45,1,1,7,1,Unknown,51,0,8,0,0,0,197,157,250,5,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Ch,Yes,NO,87
5,Caucasian,Male,55,2,1,2,3,Unknown,31,6,16,0,0,0,414,411,250,9,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Yes,>30,87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101760,AfricanAmerican,Female,65,1,1,7,6,Unknown,45,1,25,3,1,2,345,438,412,9,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,87
101761,AfricanAmerican,Male,75,1,3,7,3,Unknown,51,0,16,0,0,0,250.13,291,458,9,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,>30,87
101763,Caucasian,Male,75,1,1,7,1,Unknown,53,0,9,1,0,0,38,590,296,13,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Down,No,No,No,No,No,Ch,Yes,NO,87
101764,Caucasian,Female,85,2,3,7,10,Surgery-General,45,2,21,0,0,1,996,285,998,9,No,No,No,No,No,No,Steady,No,No,Steady,No,No,No,No,No,No,No,Up,No,No,No,No,No,Ch,Yes,NO,62
101765,Caucasian,Male,75,1,1,7,6,Unknown,13,3,3,0,0,0,530,530,787,9,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NO,87

In [149]:
# Check for duplicate rows

df.duplicated().sum()

np.int64(0)

In [150]:
import os

os.makedirs("../HOSPITALDATA/processed", exist_ok=True)

In [151]:
df.to_csv(
    "../HOSPITALDATA/processed/cleaned_sales_data.csv",
    index=False
)